FROM python:3.8.1

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it postgresql-client redis-tools

WORKDIR /app
COPY requirements/ .
COPY writer/requirements.txt .
RUN pip install -U -r requirements-testing.txt
COPY scripts/ .
COPY writer/.coveragerc .
COPY writer/entrypoint.sh .
ENV PYTHONPATH /app/

ENTRYPOINT ["./entrypoint.sh"]
CMD ["pytest"]
