FROM python:3.7

RUN apt-get -y update && apt-get -y upgrade && \
   apt-get install --no-install-recommends -y wait-for-it

WORKDIR /app
COPY requirements-development.txt .
RUN pip install -U -r requirements-development.txt
ENV PYTHONPATH /app/

CMD ["pytest"]
