version: "3"
services:
    reader:
        build:
            target: "dev"
            args:
                CONTEXT: "dev"
                MODULE: "reader"
                PORT: "9010"
        image: openslides-datastore-reader-dev
        volumes:
            - ./datastore:/app/datastore
            - ./tests:/app/tests
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        environment:
            - OPENSLIDES_DEVELOPMENT=1
        depends_on:
            - postgres
        networks:
            - postgres
        stdin_open: true
        tty: true
    writer:
        build:
            target: "dev"
            args:
                CONTEXT: "dev"
                MODULE: "writer"
                PORT: "9011"
        image: openslides-datastore-writer-dev
        volumes:
            - ./datastore:/app/datastore
            - ./tests:/app/tests
            - ./cli:/app/cli
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        environment:
            - OPENSLIDES_DEVELOPMENT=1
        depends_on:
            - postgres
            - redis
        networks:
            - postgres
            - redis
        stdin_open: true
        tty: true
    postgres:
        image: postgres:15
        env_file: database.env
        networks:
            - postgres
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    postgres:
    redis:
