version: '3'
services:
    reader:
        image: openslides-datastore-reader-dev
        volumes:
            - ./datastore:/app/datastore
            - ./tests:/app/tests
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        environment:
            - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
        depends_on:
            - postgresql
        networks:
            - postgresql
        stdin_open: true
        tty: true
    writer:
        image: openslides-datastore-writer-dev
        volumes:
            - ./datastore:/app/datastore
            - ./tests:/app/tests
            - ./cli:/app/cli
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        environment:
            - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
            - COMMAND=create_initial_data
            - DATASTORE_INITIAL_DATA_FILE=https://raw.githubusercontent.com/OpenSlides/OpenSlides/openslides4-dev/docs/example-data.json
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
        stdin_open: true
        tty: true
    postgresql:
        image: postgres:11
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    postgresql:
    redis: