version: "3"
services:
    reader:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git#main"
            dockerfile: Dockerfile
            target: "dev"
            args:
                MODULE: "reader"
                PORT: "9010"
                CONTEXT: "dev"
        image: openslides-datastore-reader
        ports:
            - "9010:9010"
        environment:
            - OPENSLIDES_DEVELOPMENT=1
        depends_on:
            - postgres
        networks:
            - datastore
            - postgres
    writer:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git#main"
            dockerfile: Dockerfile
            target: "dev"
            args:
                MODULE: "writer"
                PORT: "9011"
                CONTEXT: "dev"
        image: openslides-datastore-writer
        ports:
            - "9011:9011"
        environment:
            - OPENSLIDES_DEVELOPMENT=1
        depends_on:
            - postgres
            - redis
        networks:
            - datastore
            - postgres
            - redis
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
        networks:
            - postgres
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    datastore:
    postgres:
    redis:
