version: "3"
services:

    collector:
        image: otel/opentelemetry-collector:0.41.0
        command: ["--config=/etc/otel-collector-config.yml"]
        volumes:
            - type: bind
              source: ./otel-collector-config.yml
              target: /etc/otel-collector-config.yml
        networks:
            - otel

    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - "16686:16686"
        networks:
            - otel

    datastore:
        networks:
            - otel
networks:
    otel:
