version: '3'
services:
    datastore:
        image: openslides-datastore-test
        command: ["sleep", "infinity"]
        volumes:
            - ./datastore:/app/datastore
            - ./tests:/app/tests
            - ./cli:/app/cli
        environment:
            - OPENSLIDES_DEVELOPMENT=1
        depends_on:
            - postgres
            - redis
        networks:
            - postgres
            - redis
        ports:
            - "5679:5678"
    postgres:
        image: postgres:11
        env_file: database.env
        networks:
            - postgres
    redis:
        image: redis:alpine
        networks:
            - redis
networks:
    postgres:
    redis: