version: '3'
services:
    datastore:
        image: openslides-datastore-test
        command: ["sleep", "infinity"]
        volumes:
            - ./datastore:/app/datastore
            - ./tests:/app/tests
            - ./cli:/app/cli
        environment:
            - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
    postgresql:
        image: postgres:11
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        networks:
            - redis
networks:
    postgresql:
    redis: