FROM python:3.8.5-slim-buster

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it gcc libpq-dev libc-dev postgresql-client redis-tools

WORKDIR /app
ENV PYTHONPATH /app/
COPY requirements/ .

RUN pip install -U -r requirements-testing.txt

COPY scripts/* scripts/system/* tests/entrypoint.sh ./
COPY scripts/ci/* ./ci/

ENTRYPOINT ["./entrypoint.sh"]
CMD ["pytest"]
