FROM python:3.10.13-slim-bookworm

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it vim gcc libpq-dev libc-dev postgresql-client redis-tools curl

WORKDIR /app
ENV PYTHONPATH /app/
COPY requirements/ .

RUN pip install -U -r requirements-testing.txt

COPY scripts/* scripts/system/* tests/entrypoint.sh ./
COPY scripts/ci/* ./ci/

STOPSIGNAL SIGKILL
ENTRYPOINT ["./entrypoint.sh"]
CMD ["sleep", "inf"]
