FROM python:3.8.5-slim-buster

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it gcc libpq-dev libc-dev postgresql-client redis-tools

WORKDIR /app
COPY requirements/requirements-general.txt scripts/system/* ./

RUN pip install -U -r requirements-general.txt

ARG MODULE
RUN test -n "$MODULE" || (echo "MODULE not set" && false)

COPY $MODULE/entrypoint.sh ./

ENV PYTHONPATH /app/

ENV FLASK_APP=datastore.$MODULE.app
ENV FLASK_ENV=development

RUN mkdir -p /run/secrets
RUN echo -n openslides >/run/secrets/datastore_database_user_file
RUN echo -n openslides >/run/secrets/datastore_database_password_file

ARG PORT
RUN test -n "$PORT" || (echo "PORT not set" && false)
ENV PORT=$PORT

EXPOSE $PORT

ENTRYPOINT ["./entrypoint.sh"]
CMD flask run --host 0.0.0.0 --port $PORT
