FROM python:3.8.5-slim-buster

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it gcc libpq-dev libc-dev postgresql-client redis-tools

WORKDIR /app
ENV PYTHONPATH /app/
COPY requirements/ .

ARG MODULE
RUN test -n "$MODULE" || (echo "MODULE not set" && false)

COPY $MODULE/requirements.txt .

RUN pip install -U -r requirements-testing.txt

COPY scripts/* scripts/system/* $MODULE/.coveragerc $MODULE/entrypoint.sh ./

ENTRYPOINT ["./entrypoint.sh"]
CMD ["pytest"]
