version: '3.4'
services:
    reader:
        image: openslides-datastore-reader
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        environment:
            - PORT=${OPENSLIDES_DATASTORE_READER_PORT}
            - NUM_WORKERS=8
        depends_on:
            - postgres
        networks:
            - postgres
        secrets:
            - postgres_password
    writer:
        image: openslides-datastore-writer
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        environment:
            - PORT=${OPENSLIDES_DATASTORE_WRITER_PORT}
        depends_on:
            - postgres
            - redis
        networks:
            - postgres
            - redis
        secrets:
            - postgres_password
    postgres:
        image: postgres:11
        env_file: database.env
        networks:
            - postgres
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    postgres:
    redis:
secrets:
    postgres_password:
        file: ./secrets/postgres_password