FROM python:3.8.1

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it postgresql-client redis-tools

WORKDIR /app
COPY requirements/requirements-general.txt scripts/system/* ./

ARG MODULE
RUN test -n "$MODULE" || (echo "MODULE not set" && false)

COPY $MODULE/requirements.txt $MODULE/entrypoint.sh ./
RUN pip install -U -r requirements-general.txt

ENV PYTHONPATH /app/

ENV FLASK_APP=$MODULE.app
ENV FLASK_ENV=development

ARG COMMAND
ENV COMMAND=$COMMAND

ENTRYPOINT ["./entrypoint.sh"]

ARG PORT
RUN test -n "$PORT" || (echo "PORT not set" && false)
ENV PORT=$PORT

ENTRYPOINT ["./entrypoint.sh"]
CMD flask run --host 0.0.0.0 --port $PORT
