version: '3.7'
services:
    reader:
        build:
            context: .
            target: reader
        ports:
            - 9010:9010
        environment:
            - NUM_WORKERS=8
        depends_on:
            - postgresql
        networks:
            - postgresql
    writer:
        build:
            context: .
            target: writer
        ports:
            - 9011:9011
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
    postgresql:
        image: sameersbn/postgresql:10
        labels:
            org.openslides.role: "postgres"
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    postgresql:
    redis:
