version: '3.4'
services:
    reader:
        image: openslides-datastore-reader
        ports:
            - "${OPENSLIDES_DATASTORE_READER_PORT}:${OPENSLIDES_DATASTORE_READER_PORT}"
        environment:
            - PORT=${OPENSLIDES_DATASTORE_READER_PORT}
            - NUM_WORKERS=8
            - DATASTORE_DATABASE_USER=/run/secrets/datastore_postgres_user
            - DATASTORE_DATABASE_PASSWORD=/run/secrets/datastore_postgres_password
        depends_on:
            - postgresql
        networks:
            - postgresql
        secrets:
            - datastore_postgres_user
            - datastore_postgres_password
    writer:
        image: openslides-datastore-writer
        ports:
            - "${OPENSLIDES_DATASTORE_WRITER_PORT}:${OPENSLIDES_DATASTORE_WRITER_PORT}"
        environment:
            - PORT=${OPENSLIDES_DATASTORE_WRITER_PORT}
            - DATASTORE_DATABASE_USER=/run/secrets/datastore_postgres_user
            - DATASTORE_DATABASE_PASSWORD=/run/secrets/datastore_postgres_password
        depends_on:
            - postgresql
            - redis
        networks:
            - postgresql
            - redis
        secrets:
            - datastore_postgres_user
            - datastore_postgres_password
    postgresql:
        image: postgres:11
        env_file: database.env
        networks:
            - postgresql
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - redis
networks:
    postgresql:
    redis:
secrets:
    datastore_postgres_user:
        file: ./secrets/datastore_postgres_user
    datastore_postgres_password:
        file: ./secrets/datastore_postgres_password