FROM python:3.8.1

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it postgresql-client

WORKDIR /app
COPY requirements/ .
RUN touch requirements.txt
RUN pip install -U -r requirements-testing.txt
COPY scripts/ .
COPY shared/.coveragerc .
ENV PYTHONPATH /app/

CMD ["pytest"]
