FROM python:3.8.1

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it postgresql-client

WORKDIR /app
COPY requirements/ .
RUN pip install -U -r requirements-testing.txt -r requirements.txt
COPY scripts/ .
ENV PYTHONPATH /app/

CMD ["pytest"]
